// Generated from `supabase gen types typescript --local --schema public`.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = { public: { Tables: {
  books: { Row: { author: string; cover_url: string | null; created_at: string; current_page: number; date_added: string; date_completed: string | null; id: string; status: string; title: string; total_pages: number; updated_at: string; user_id: string }; Insert: { author: string; cover_url?: string | null; created_at?: string; current_page?: number; date_added?: string; date_completed?: string | null; id?: string; status?: string; title: string; total_pages: number; updated_at?: string; user_id?: string }; Update: { author?: string; cover_url?: string | null; created_at?: string; current_page?: number; date_added?: string; date_completed?: string | null; id?: string; status?: string; title?: string; total_pages?: number; updated_at?: string; user_id?: string }; Relationships: [] };
  profiles: { Row: { avatar_url: string | null; created_at: string; display_name: string; id: string; time_zone: string; updated_at: string }; Insert: { avatar_url?: string | null; created_at?: string; display_name?: string; id: string; time_zone?: string; updated_at?: string }; Update: { avatar_url?: string | null; created_at?: string; display_name?: string; id?: string; time_zone?: string; updated_at?: string }; Relationships: [] };
  quotes: { Row: { book_id: string; created_at: string; id: string; session_id: string | null; text: string; updated_at: string; user_id: string }; Insert: { book_id: string; created_at?: string; id?: string; session_id?: string | null; text: string; updated_at?: string; user_id?: string }; Update: { book_id?: string; created_at?: string; id?: string; session_id?: string | null; text?: string; updated_at?: string; user_id?: string }; Relationships: [{ foreignKeyName: "quotes_book_owner_fk"; columns: ["book_id", "user_id"]; isOneToOne: false; referencedRelation: "books"; referencedColumns: ["id", "user_id"] }, { foreignKeyName: "quotes_session_owner_fk"; columns: ["session_id", "user_id"]; isOneToOne: false; referencedRelation: "reading_sessions"; referencedColumns: ["id", "user_id"] }] };
  reading_plans: { Row: { book_id: string; created_at: string; id: string; note: string | null; planned_date: string; target_minutes: number | null; target_pages: number | null; updated_at: string; user_id: string }; Insert: { book_id: string; created_at?: string; id?: string; note?: string | null; planned_date: string; target_minutes?: number | null; target_pages?: number | null; updated_at?: string; user_id?: string }; Update: { book_id?: string; created_at?: string; id?: string; note?: string | null; planned_date?: string; target_minutes?: number | null; target_pages?: number | null; updated_at?: string; user_id?: string }; Relationships: [{ foreignKeyName: "reading_plans_book_owner_fk"; columns: ["book_id", "user_id"]; isOneToOne: false; referencedRelation: "books"; referencedColumns: ["id", "user_id"] }] };
  reading_sessions: { Row: { book_id: string; created_at: string; duration_seconds: number; ended_at: string | null; id: string; mood_tags: string[]; reflection_prompt: string | null; reflection_text: string | null; session_local_date: string; started_at: string; time_zone: string; updated_at: string; user_id: string; xp_earned: number }; Insert: { book_id: string; created_at?: string; duration_seconds: number; ended_at?: string | null; id?: string; mood_tags?: string[]; reflection_prompt?: string | null; reflection_text?: string | null; session_local_date: string; started_at?: string; time_zone: string; updated_at?: string; user_id?: string; xp_earned?: number }; Update: { book_id?: string; created_at?: string; duration_seconds?: number; ended_at?: string | null; id?: string; mood_tags?: string[]; reflection_prompt?: string | null; reflection_text?: string | null; session_local_date?: string; started_at?: string; time_zone?: string; updated_at?: string; user_id?: string; xp_earned?: number }; Relationships: [{ foreignKeyName: "reading_sessions_book_owner_fk"; columns: ["book_id", "user_id"]; isOneToOne: false; referencedRelation: "books"; referencedColumns: ["id", "user_id"] }] };
  session_notes: { Row: { book_id: string; chapter_reference: string | null; content: string; created_at: string; id: string; session_id: string | null; tags: string[]; title: string; updated_at: string; user_id: string }; Insert: { book_id: string; chapter_reference?: string | null; content?: string; created_at?: string; id?: string; session_id?: string | null; tags?: string[]; title: string; updated_at?: string; user_id?: string }; Update: { book_id?: string; chapter_reference?: string | null; content?: string; created_at?: string; id?: string; session_id?: string | null; tags?: string[]; title?: string; updated_at?: string; user_id?: string }; Relationships: [{ foreignKeyName: "session_notes_book_owner_fk"; columns: ["book_id", "user_id"]; isOneToOne: false; referencedRelation: "books"; referencedColumns: ["id", "user_id"] }, { foreignKeyName: "session_notes_session_owner_fk"; columns: ["session_id", "user_id"]; isOneToOne: false; referencedRelation: "reading_sessions"; referencedColumns: ["id", "user_id"] }] };
  streak_freezes: { Row: { created_at: string; id: string; missed_date: string; month_start: string; user_id: string }; Insert: { created_at?: string; id?: string; missed_date: string; month_start: string; user_id: string }; Update: { created_at?: string; id?: string; missed_date?: string; month_start?: string; user_id?: string }; Relationships: [] };
  user_stats: { Row: { current_streak: number; last_session_date: string | null; longest_streak: number; total_seconds: number; total_sessions: number; total_xp: number; updated_at: string; user_id: string }; Insert: { current_streak?: number; last_session_date?: string | null; longest_streak?: number; total_seconds?: number; total_sessions?: number; total_xp?: number; updated_at?: string; user_id: string }; Update: { current_streak?: number; last_session_date?: string | null; longest_streak?: number; total_seconds?: number; total_sessions?: number; total_xp?: number; updated_at?: string; user_id?: string }; Relationships: [] };
}; Views: { [_ in never]: never }; Functions: { finalize_reading_session: { Args: { p_book_id: string; p_chapter_reference?: string; p_duration_seconds: number; p_mood_tags?: string[]; p_note_content?: string; p_note_tags?: string[]; p_note_title?: string; p_quote_text?: string; p_reflection_prompt?: string; p_reflection_text?: string; p_started_at?: string; p_time_zone?: string }; Returns: { session_id: string; xp_earned: number }[] } }; Enums: { [_ in never]: never }; CompositeTypes: { [_ in never]: never } } };

type PublicSchema = Database["public"];
export type Tables<Name extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][Name]["Row"];
export type TablesInsert<Name extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][Name]["Insert"];
export type TablesUpdate<Name extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][Name]["Update"];
